version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.5
        environment:
          DATABASE_URL: postgresql://postgres:secret@localhost:5432/rails-pg-extras-test
      - image: pawurb/postgres-stat-statements
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: rails-pg-extras-test
          POSTGRES_PASSWORD: secret
    parallelism: 1
    steps:
      - checkout
      - run: gem update --system
      - run: gem install bundler
      - run: bundle install --path vendor/bundle
      - run: sudo apt install postgresql-client
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Run specs
          command: |
            bundle exec rspec spec/
workflows:
  version: 2
  test:
    jobs:
      - test
